import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import { MakeswiftProvider } from '@/makeswift/provider';
import { DraftModeScript } from '@makeswift/runtime/next/server';
import '@/makeswift/components';
import '../globals.css';
import { draftMode } from 'next/headers';
import { SettingsProvider } from '@/contexts/settings';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const dmSans = DM_Sans({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <DraftModeScript />
      </head>
      <body className={inter.className + ' ' + dmSans.className}>
        <SettingsProvider>
          <MakeswiftProvider previewMode={(await draftMode()).isEnabled}>
            {children}
          </MakeswiftProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
